cc_library(
    name = "eve_stuff",
    srcs = [
        "src/outdatedHistories.cpp",
        "src/outdatedOrders.cpp",
    ],
    hdrs = [
        "include/outdatedOrders.h",
        "include/outdatedHistories.h",
    ],
    strip_include_prefix = "include",
    deps = ["@boost//:numeric"],
)

