cc_library(
    name = "eve_stuff",
    srcs = [
        "outdatedHistories.cpp",
        "outdatedOrders.cpp",
    ],
    hdrs = [
        "outdatedHistories.h",
        "outdatedOrders.h",
    ],
    visibility = ["//apps:__pkg__"],
    deps = [
        "//libs/profiling",
        "//libs/sqlite-util:sqlite_util",
    ],
)
