cc_library(
    name = "yaml_fwd",
    hdrs = [
        "include/yaml_fwd.h",
    ],
    strip_include_prefix = "include",
    visibility = [
        "//libs/groups:__pkg__",
        "//libs/industry_resources/copying:__pkg__",
        "//libs/industry_resources/production:__pkg__",
        "//libs/industry_resources/research:__pkg__",
        "//libs/industry_resources/types:__pkg__",
        "//libs/names:__pkg__",
        "//libs/settings:__pkg__",
    ],
)
