cc_library(
    name = "access_token",
    srcs = [
        "access_token.cpp",
    ],
    hdrs = [
        "access_token.h",
    ],
    linkopts = ["-lboost_regex"],
    deps = [
        "//libs/HTTPSRequestHandler:https_request_handler",
    ],
)
