cc_library(
    name = "semaphore",
    srcs = [
        "src/Semaphore.cpp",
    ],
    hdrs = [
        "include/Semaphore.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//apps:__pkg__"],
)
