cc_library(
    name = "sqlit_util",
    srcs = [
        "src/sqlite.cpp",
    ],
    hdrs = [
        "include/sqlite.h",
    ],
    strip_include_prefix = "include",
    deps = ["@boost//:numeric"],
)
