cc_library(
    name = "profiling",
    hdrs = [
        "include/profiling.h",
    ],
    includes = ["include"],
    visibility = [
        "//apps:__pkg__",
        "//apps/price_reader:__pkg__",
        "//libs/eve_stuff:__pkg__",
        "//libs/groups:__pkg__",
        "//libs/names:__pkg__",
        "//libs/settings:__pkg__",
    ],
)
