cc_library(
    name = "infinity",
    hdrs = [
        "include/infinity.h",
    ],
    strip_include_prefix = "include",
    visibility = [
        "//libs/industry_resources:__pkg__",
        "//libs/infinity/test:__pkg__",
    ],
)
