cc_library(
    name = "types",
    srcs = [
        "src/types.cpp",
    ],
    hdrs = [
        "include/types.h",
    ],
    strip_include_prefix = "include",
    visibility = [
        "//libs/industry_resources/resource_manager:__pkg__",
    ],
    deps = [
        "//libs/groups",
        "//libs/industry_resources:type_id",
        "//libs/yaml_fwd",
    ],
)
