cc_library(
    name = "types",
    srcs = [
        "types.cpp",
    ],
    hdrs = [
        "types.h",
    ],
    visibility = [
        "//libs/industry_resources/resource_manager:__pkg__",
    ],
    deps = [
        "//libs/groups",
        "//libs/industry_resources:type_id",
        "//libs/yaml_fwd",
    ],
)
