cc_library(
    name = "skills",
    srcs = [
        "skills.cpp",
    ],
    hdrs = [
        "skills.h",
    ],
    visibility = [
        "//libs/industry_resources/copying:__pkg__",
        "//libs/industry_resources/production:__pkg__",
        "//libs/industry_resources/research:__pkg__",
    ],
    deps = [
        "//libs/names",
    ],
)
