cc_library(
    name = "skills",
    srcs = [
        "src/skills.cpp",
    ],
    hdrs = [
        "include/skills.h",
    ],
    strip_include_prefix = "include",
    visibility = [
        "//libs/industry_resources/copying:__pkg__",
        "//libs/industry_resources/production:__pkg__",
        "//libs/industry_resources/research:__pkg__",
    ],
    deps = [
        "//libs/names",
    ],
)
